### ISSUE TITLE
Data/Code for Core Risk Minimization

### ISSUE THREAD

**Issue by erobic** [singlasahil14/salient_imagenet#1]
Firstly, a huge thank you for the core/spurious feature annotations. 

Do you have a tentative date when the data and code for the follow-up work: Core Risk Minimization will be released? I am interested in leveraging the masks for my own studies, so eagerly waiting for the release!

**Comment by singlasahil14** [comment]
It should happen in a few weeks. I will try to do it as soon as possible!

**Comment by SnowdenLee** [comment]
Hi, 
thanks for the great work. Following up on this issue, do you still have any plan to release the code for Core Risk Minimization? Thank you very much!
